baseurl = "http://scriptinspector.org"
languageCode = "en-us"
title = "ScriptInspector"
subtitle = "Understanding and Monitoring Embedded Web Scripts"

[params]
    sidebartitle = "Script\nInspector"
    sidebartagline = "Understanding and Monitoring Embedded Web Scripts"
    nodate = true
    noauthor = true
    noread = true
    nopaging=true
    notoc=true

[[menu.main]]
name = "Advice"
url = "/advice"

[[menu.main]]
name = "Time"
url = "/time"

[[menu.main]]
name = "Teaching"
url = "/teaching"

[[menu.main]]
name = "Research"
url = "/research"

[[menu.footer]]
